### ISSUE TITLE
This looks great.  I would like to verify correct unit before flashing

### ISSUE THREAD

**Issue by bobbitchin** [wertwert4pda/rt5350f-uboot#1]
I'd like to use this, but want to make sure I have this device.  What I have is this one:

https://wiki.openwrt.org/toh/unbranded/a5-v11

It has 4MB flash, 32MB RAM and the English/Chinese Qualcom interface.

I'm thinking of following this guide, using the same OpenWRT firmware but with your u-boot (uboot_usb_256_03.img):
http://my-embedded.blogspot.com/2014/01/mini-usb-portable-3g4g-router-rt5350f.html

Does this sound like a reasonable plan?

**Comment by wertwert4pda** [comment]
Yes. It was tested on 4MB FLASH, 32MB RAM, English/Chinese Qualcomm interface.
It look as a picture on https://wiki.openwrt.org/toh/unbranded/a5-v11

**Comment by bobbitchin** [comment]
It works great!  Using the blue LED was also a very good idea.  I followed the guide I posted using the USB drive.  On the root of the drive I had the OpenWRT sysupgrade.bin renamed firmware.bin.  I powered on with reset down, the blue LED came on, bunch of flashing, rebooted itself and running.  Thanks for this, it really makes it easier to get OpenWRT on there.
